name: C++ Client Build

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies (brew)
      run: |
        brew install cmake sdl3 sdl3_image sdl3_ttf nlohmann-json

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build --config Release
